name: CD - Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - 'Dockerfile'

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        # We pass all necessary variables here to prevent interactive prompts
        run: |
          terraform plan -out=tfplan \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="db_host=${{ secrets.DB_HOST }}" \
            -var="db_name=strapi" \
            -var="db_user=postgres" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="ecs_sg_id=${{ secrets.ECS_SG_ID }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan